{
    "name": "CM Invoice Batches",
    "version": "19.0.0.1",
    "category": "Industries",
    "summary": "Invoice aggregation workflows for Cell Mechanic",
    "description": "Weekly and monthly invoice batch tracking for BOCES workflows.",
    "author": "Shiny Computers",
    "maintainers": ["cbusillo"],
    "license": "LGPL-3",
    "depends": [
        "account",
        "base",
        "cm_device",
        "cm_quality_control",
        "cm_repair",
        "helpdesk",
        "mail",
        "cm_school",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/stage_data.xml",
        "views/invoice_order_views.xml",
        "views/invoice_note_template_views.xml",
        "views/call_authorization_views.xml",
        "views/invoice_batch_views.xml",
        "views/cm_invoice_batch_actions.xml",
        "views/device_views.xml",
    ],
    "installable": True,
    "application": False,
}
