# Project-specific Codex configuration for Odoo OPW

# Default model and settings
model = "gpt-5"
approval_policy = "never"
sandbox_mode = "workspace-write"

# Project documentation to include
project_doc = "CODEX.md"
project_doc_max_bytes = 32768

# Note: Profiles must be defined in ~/.codex/config.toml (global config)
# Available profiles: deep-reasoning, dev-standard, safe-readonly

# Shell environment configuration
[shell_environment_policy]
inherit = "all"
set = { PYTHONPATH = "/volumes/addons:/odoo/addons:/volumes/enterprise", DATABASE = "opw" }

# Sandbox configuration
[sandbox_workspace_write]
network_access = false
exclude_tmpdir_env_var = false
exclude_slash_tmp = false

[mcp_servers.odoo-intelligence]
command = "uv"
args = ["run", "--project", "/Users/cbusillo/Developer/odoo-intelligence-mcp", "odoo-intelligence-mcp"]

[mcp_servers.inspection-pycharm]
command = "node"
args = ["/Users/cbusillo/Developer/jetbrains-inspection-api/mcp-server/server.js"]
