{
    "name": "Cell Mechanic Custom",
    "version": "18.0.0.1",
    "category": "Industries",
    "summary": "Custom features for CellMechanic repair operations",
    "description": "Custom module for CellMechanic's phone repair business operations.",
    "author": "Justin Millman (Cell Mechanic), Chris Busillo (Shiny Computers)",
    "maintainers": ["cellmechanic", "cbusillo"],
    "website": "https://cellmechanic.com",
    "depends": [
        "base",
        "mail",
        "product",
        "account",
        "external_ids",
        "hr_employee_name_extended",
        "disable_odoo_online",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/cm_custom_menus.xml",
        "views/transport_order_views.xml",
        "views/intake_order_views.xml",
        "views/diagnostic_order_views.xml",
        "views/repair_batch_views.xml",
        "views/device_views.xml",
        "views/res_partner_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
