webhook_secret_file = "/opt/odoo-automation/secrets/github-webhook.txt"

[[stacks]]
name = "opw-dev"
stack_root = "/opt/opw-dev"
healthcheck = "http://localhost:18069/web/login"

[[stacks]]
name = "opw-testing"
stack_root = "/opt/opw-testing"
healthcheck = "http://localhost:28069/web/login"

[[routes]]
repository = "odoo-ai"
branch = "main"
stack = "opw-testing"
lane = "core"

[[routes]]
repository = "*"
branch = "dev"
stack = "opw-dev"

[[routes]]
repository = "*"
branch = "testing"
stack = "opw-testing"
