{
    "name": "Fishbowl Import",
    "version": "19.0.0.2",
    "category": "Tools",
    "summary": "Import Fishbowl data into Odoo",
    "description": "Import Fishbowl customers, vendors, products, orders, and inventory history.",
    "author": "Shiny Computers",
    "maintainers": ["cbusillo"],
    "license": "LGPL-3",
    "depends": [
        "base",
        "product",
        "stock",
        "sale",
        "purchase",
        "external_ids",
        "transaction_utilities",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        "views/stock_picking_views.xml",
    ],
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
}
