from . import cm_data_direction
from . import cm_data_importer
from . import cm_data_note
from . import cm_data_password
from . import cm_data_price_list
from . import cm_data_pricing_audit
from . import cm_data_shipping_instruction
from . import cm_data_pto_usage
from . import cm_data_vacation_usage
from . import cm_seed_loader
from . import hr_employee
from . import hr_attendance
from . import res_partner
