{
    "name": "Marine Motors",
    "version": "19.0.1.0",
    "category": "Industries",
    "author": "Shiny Computers",
    "maintainers": ["cbusillo"],
    "depends": [
        "base",
        "product",
        "mail",
        "repair",
        "stock",
        "web",
        "website_sale",
        "product_metadata",
        "product_widgets",
        "image_enhancements",
        "notification_center",
        "web_tour",
    ],
    "summary": "Motor teardown and parts workflows for marine inventory",
    "data": [
        "security/ir.model.access.csv",
        "data/motor_test_section_data.xml",
        "data/motor_test_selection_data.xml",
        "data/motor_test_template_data.xml",
        "data/motor_part_template_data.xml",
        "data/motor_stat_data.xml",
        "data/mail_templates.xml",
        "report/motor_product_reports.xml",
        "report/motor_reports.xml",
        "views/motor_views.xml",
        "views/motor_part_template_views.xml",
        "views/motor_product_template_views.xml",
        "views/motor_product_views.xml",
        "views/motor_test_template_views.xml",
        "views/motor_test_selection_views.xml",
        "views/motor_test_section_views.xml",
        "views/printnode_interface_views.xml",
        "views/product_template_views.xml",
        "views/repair_order_views.xml",
        "views/res_users_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "marine_motors/static/src/scss/motor.scss",
            "marine_motors/static/src/js/forms/motor_form.js",
            "marine_motors/static/src/js/widgets/resettable_badge_selection_widget.js",
            "marine_motors/static/src/js/widgets/motor_test_widget.js",
            "marine_motors/static/src/xml/motor_test_widget.xml",
            "marine_motors/static/src/xml/resettable_badge_selection_widget.xml",
        ],
        "web.assets_tests": [
            "marine_motors/static/tests/tours/**/*.js",
        ],
    },
    "pre_init_hook": "pre_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
