# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/product_connect/graphql/shopify

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserErrorFields


class DeleteProduct(BaseModel):
    product_delete: Optional["DeleteProductProductDelete"] = Field(
        alias="productDelete"
    )


class DeleteProductProductDelete(BaseModel):
    deleted_product_id: Optional[str] = Field(alias="deletedProductId")
    user_errors: list["DeleteProductProductDeleteUserErrors"] = Field(
        alias="userErrors"
    )


class DeleteProductProductDeleteUserErrors(UserErrorFields):
    pass


DeleteProduct.model_rebuild()
DeleteProductProductDelete.model_rebuild()
