# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/product_connect/graphql/shopify

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import CustomerFields


class GetCustomers(BaseModel):
    customers: "GetCustomersCustomers"


class GetCustomersCustomers(BaseModel):
    page_info: "GetCustomersCustomersPageInfo" = Field(alias="pageInfo")
    nodes: list["GetCustomersCustomersNodes"]


class GetCustomersCustomersPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class GetCustomersCustomersNodes(CustomerFields):
    pass


GetCustomers.model_rebuild()
GetCustomersCustomers.model_rebuild()
