# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/product_connect/graphql/shopify

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ProductReorderMedia(BaseModel):
    product_reorder_media: Optional["ProductReorderMediaProductReorderMedia"] = Field(
        alias="productReorderMedia"
    )


class ProductReorderMediaProductReorderMedia(BaseModel):
    job: Optional["ProductReorderMediaProductReorderMediaJob"]
    media_user_errors: list["ProductReorderMediaProductReorderMediaMediaUserErrors"] = (
        Field(alias="mediaUserErrors")
    )


class ProductReorderMediaProductReorderMediaJob(BaseModel):
    id: str
    done: bool


class ProductReorderMediaProductReorderMediaMediaUserErrors(BaseModel):
    field: Optional[list[str]]
    message: str


ProductReorderMedia.model_rebuild()
ProductReorderMediaProductReorderMedia.model_rebuild()
