# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/product_connect/graphql/shopify

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserErrorFields


class UpdatePublications(BaseModel):
    publishable_publish: Optional["UpdatePublicationsPublishablePublish"] = Field(
        alias="publishablePublish"
    )


class UpdatePublicationsPublishablePublish(BaseModel):
    user_errors: list["UpdatePublicationsPublishablePublishUserErrors"] = Field(
        alias="userErrors"
    )


class UpdatePublicationsPublishablePublishUserErrors(UserErrorFields):
    pass


UpdatePublications.model_rebuild()
UpdatePublicationsPublishablePublish.model_rebuild()
