- name: Deploy Shiny K3s cluster
  hosts: shiny_cluster
  become: true
  roles:
    - role: xanmanning.k3s
      k3s_become: true
      vars:
        k3s_cluster_domain: shiny.cluster
        k3s_server:
          tls-san:
            - "{{ inventory_hostname }}"
            - "{{ inventory_hostname }}.shiny"

- name: Deploy OPW K3s cluster
  hosts: opw_cluster
  become: true
  roles:
    - role: xanmanning.k3s
      k3s_become: true
      vars:
        k3s_cluster_domain: opw.cluster
        k3s_server:
          tls-san:
            - "{{ inventory_hostname }}"
            - "{{ inventory_hostname }}.opw"

- name: Deploy Mike K3s cluster
  hosts: mike_cluster
  become: true
  roles:
    - role: xanmanning.k3s
      k3s_become: true
      vars:
        k3s_cluster_domain: mike.cluster
        k3s_server:
          tls-san:
            - "{{ inventory_hostname }}"
            - "{{ inventory_hostname }}.mike"

- name: Download kubeconfig files from master servers
  hosts:
    - shiny_servers[0]
    - opw_servers[0]
    - mike_servers[0]
  become: true
  tasks:
    - name: Determine the cluster name for each host
      set_fact:
        cluster_name: "{{ (group_names | select('match', '.*_cluster$') | list | first) | regex_replace('_cluster$', '') }}"

    - name: Fetch kubeconfig from master nodes
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "~/.kube/{{ cluster_name }}.yaml"
        flat: yes

    - name: Replace server address in kubeconfig files
      delegate_to: localhost
      become: false
      replace:
        path: "~/.kube/{{ cluster_name }}.yaml"
        regexp: 'https://127.0.0.1:6443'
        replace: 'https://{{ inventory_hostname }}:6443'

    - name: Load kubeconfig YAML into variable
      delegate_to: localhost
      become: false
      slurp:
        src: "~/.kube/{{ cluster_name }}.yaml"
      register: kubeconfig_raw

    - name: Update kubeconfig with custom cluster name
      delegate_to: localhost
      become: false
      set_fact:
        kubeconfig_content: "{{ kubeconfig_raw.content | b64decode | from_yaml }}"

    - name: Set cluster and context names clearly for Lens
      delegate_to: localhost
      become: false
      copy:
        dest: "~/.kube/{{ cluster_name }}.yaml"
        content: |
          {{ kubeconfig_content
            | combine({
              'clusters': [{'name': cluster_name, 'cluster': kubeconfig_content.clusters[0].cluster}],
              'contexts': [{'name': cluster_name, 'context': {'cluster': cluster_name, 'user': kubeconfig_content.contexts[0].context.user}}],
              'current-context': cluster_name
            }) | to_nice_yaml }}