- name: Configure Linux power settings on all cluster hosts
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Ensure logind config directory exists
      ansible.builtin.file:
        path: /etc/systemd/logind.conf.d
        state: directory
        mode: '0755'
    - name: Configure lid-close actions and power settings
      copy:
        dest: /etc/systemd/logind.conf.d/lid-settings.conf
        content: |
          [Login]
          HandleLidSwitch=ignore
          HandleLidSwitchDocked=ignore
          HandleLidSwitchExternalPower=ignore
          LidSwitchIgnoreInhibited=yes

    - name: Ensure displays are powered off after inactivity (optional but recommended)
      copy:
        dest: /etc/systemd/logind.conf.d/power-saving.conf
        content: |
          [Login]
          IdleAction=ignore
          IdleActionSec=0

    - name: Restart systemd-logind to apply changes
      ansible.builtin.systemd:
        name: systemd-logind
        state: restarted

    - name: Turn off all displays by setting brightness to 0
      shell: "echo 0 | tee /sys/class/backlight/*/brightness"
      ignore_errors: yes