- import_playbook: update_known_hosts.yml

- name: Update Debian packages on node
  hosts: all
  become: true  # runs with sudo privileges
  tasks:
    - name: Run apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

- import_playbook: install_gpu.yml