- name: Update Debian packages on node
  hosts: cluster
  become: true  # runs with sudo privileges
  tasks:
    - name: Run apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
