from . import external_system
from . import external_system_url
from . import url_template_rename_wizard
from . import external_id_mixin
from . import external_id
from . import hr_employee
from . import res_partner
from . import product_template
from . import sale_order
from . import sale_order_line
from . import purchase_order
from . import purchase_order_line
from . import stock_picking
from . import stock_move
from . import uom_uom
