# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/shopify_sync/graphql/shopify

from typing import Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class CurrentBulkOperation(BaseModel):
    bulk_operations: "CurrentBulkOperationBulkOperations" = Field(
        alias="bulkOperations"
    )


class CurrentBulkOperationBulkOperations(BaseModel):
    nodes: list["CurrentBulkOperationBulkOperationsNodes"]


class CurrentBulkOperationBulkOperationsNodes(BaseModel):
    id: str
    status: BulkOperationStatus
    object_count: int = Field(alias="objectCount")
    url: Optional[AnyUrl]
    partial_data_url: Optional[AnyUrl] = Field(alias="partialDataUrl")


CurrentBulkOperation.model_rebuild()
CurrentBulkOperationBulkOperations.model_rebuild()
