# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/product_connect/graphql/shopify

from .base_model import BaseModel


class GetLocations(BaseModel):
    locations: "GetLocationsLocations"


class GetLocationsLocations(BaseModel):
    nodes: list["GetLocationsLocationsNodes"]


class GetLocationsLocationsNodes(BaseModel):
    id: str


GetLocations.model_rebuild()
GetLocationsLocations.model_rebuild()
