# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/shopify_sync/graphql/schema/shopify_schema_2026-01.sdl

from datetime import datetime
from decimal import Decimal
from typing import Annotated, Optional

from pydantic import Field, PlainSerializer

from ..helpers import format_datetime_for_shopify
from .base_model import BaseModel
from .enums import (
    CombinedListingsRole,
    CountryCode,
    FileContentType,
    FileCreateInputDuplicateResolutionMode,
    ProductStatus,
    ProductVariantInventoryPolicy,
    StagedUploadHttpMethodType,
    StagedUploadTargetGenerateUploadResource,
    UnitPriceMeasurementMeasuredUnit,
    WeightUnit,
)


class CountryHarmonizedSystemCodeInput(BaseModel):
    harmonized_system_code: str = Field(alias="harmonizedSystemCode")
    country_code: Optional[CountryCode] = Field(alias="countryCode", default=None)


class FileSetInput(BaseModel):
    filename: Optional[str] = None
    content_type: Optional[FileContentType] = Field(alias="contentType", default=None)
    alt: Optional[str] = None
    duplicate_resolution_mode: Optional[FileCreateInputDuplicateResolutionMode] = Field(
        alias="duplicateResolutionMode",
        default=FileCreateInputDuplicateResolutionMode.APPEND_UUID,
    )
    id: Optional[str] = None
    original_source: Optional[str] = Field(alias="originalSource", default=None)


class InventoryItemInput(BaseModel):
    sku: Optional[str] = None
    cost: Optional[Decimal] = None
    tracked: Optional[bool] = None
    country_code_of_origin: Optional[CountryCode] = Field(
        alias="countryCodeOfOrigin", default=None
    )
    harmonized_system_code: Optional[str] = Field(
        alias="harmonizedSystemCode", default=None
    )
    country_harmonized_system_codes: Optional[
        list["CountryHarmonizedSystemCodeInput"]
    ] = Field(alias="countryHarmonizedSystemCodes", default=None)
    province_code_of_origin: Optional[str] = Field(
        alias="provinceCodeOfOrigin", default=None
    )
    measurement: Optional["InventoryItemMeasurementInput"] = None
    requires_shipping: Optional[bool] = Field(alias="requiresShipping", default=None)


class InventoryItemMeasurementInput(BaseModel):
    weight: Optional["WeightInput"] = None
    shipping_package_id: Optional[str] = Field(alias="shippingPackageId", default=None)


class LinkedMetafieldCreateInput(BaseModel):
    namespace: str
    key: str
    values: Optional[list[str]] = None


class MetafieldInput(BaseModel):
    id: Optional[str] = None
    namespace: Optional[str] = None
    key: Optional[str] = None
    value: Optional[str] = None
    type_: Optional[str] = Field(alias="type", default=None)


class MoveInput(BaseModel):
    id: str
    new_position: int = Field(alias="newPosition")


class OptionSetInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    position: Optional[int] = None
    values: Optional[list["OptionValueSetInput"]] = None
    linked_metafield: Optional["LinkedMetafieldCreateInput"] = Field(
        alias="linkedMetafield", default=None
    )


class OptionValueSetInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class ProductClaimOwnershipInput(BaseModel):
    bundles: Optional[bool] = None


class ProductDeleteInput(BaseModel):
    id: str


class ProductSetIdentifiers(BaseModel):
    id: Optional[str] = None
    handle: Optional[str] = None
    custom_id: Optional["UniqueMetafieldValueInput"] = Field(
        alias="customId", default=None
    )


class ProductSetInput(BaseModel):
    description_html: Optional[str] = Field(alias="descriptionHtml", default=None)
    handle: Optional[str] = None
    seo: Optional["SEOInput"] = None
    product_type: Optional[str] = Field(alias="productType", default=None)
    category: Optional[str] = None
    tags: Optional[list[str]] = None
    template_suffix: Optional[str] = Field(alias="templateSuffix", default=None)
    gift_card_template_suffix: Optional[str] = Field(
        alias="giftCardTemplateSuffix", default=None
    )
    title: Optional[str] = None
    vendor: Optional[str] = None
    gift_card: Optional[bool] = Field(alias="giftCard", default=None)
    redirect_new_handle: Optional[bool] = Field(alias="redirectNewHandle", default=None)
    collections: Optional[list[str]] = None
    metafields: Optional[list["MetafieldInput"]] = None
    variants: Optional[list["ProductVariantSetInput"]] = None
    files: Optional[list["FileSetInput"]] = None
    status: Optional[ProductStatus] = None
    requires_selling_plan: Optional[bool] = Field(
        alias="requiresSellingPlan", default=None
    )
    product_options: Optional[list["OptionSetInput"]] = Field(
        alias="productOptions", default=None
    )
    claim_ownership: Optional["ProductClaimOwnershipInput"] = Field(
        alias="claimOwnership", default=None
    )
    combined_listing_role: Optional[CombinedListingsRole] = Field(
        alias="combinedListingRole", default=None
    )


class ProductSetInventoryInput(BaseModel):
    location_id: str = Field(alias="locationId")
    name: str
    quantity: int


class ProductVariantSetInput(BaseModel):
    requires_components: Optional[bool] = Field(
        alias="requiresComponents", default=None
    )
    barcode: Optional[str] = None
    compare_at_price: Optional[Decimal] = Field(alias="compareAtPrice", default=None)
    id: Optional[str] = None
    file: Optional["FileSetInput"] = None
    inventory_policy: Optional[ProductVariantInventoryPolicy] = Field(
        alias="inventoryPolicy", default=None
    )
    inventory_quantities: Optional[list["ProductSetInventoryInput"]] = Field(
        alias="inventoryQuantities", default=None
    )
    inventory_item: Optional["InventoryItemInput"] = Field(
        alias="inventoryItem", default=None
    )
    metafields: Optional[list["MetafieldInput"]] = None
    option_values: list["VariantOptionValueInput"] = Field(alias="optionValues")
    position: Optional[int] = None
    price: Optional[Decimal] = None
    sku: Optional[str] = None
    taxable: Optional[bool] = None
    tax_code: Optional[str] = Field(alias="taxCode", default=None)
    unit_price_measurement: Optional["UnitPriceMeasurementInput"] = Field(
        alias="unitPriceMeasurement", default=None
    )
    show_unit_price: Optional[bool] = Field(alias="showUnitPrice", default=None)


class PublicationInput(BaseModel):
    publication_id: Optional[str] = Field(alias="publicationId", default=None)
    publish_date: Optional[
        Annotated[datetime, PlainSerializer(format_datetime_for_shopify)]
    ] = Field(alias="publishDate", default=None)


class SEOInput(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None


class StagedUploadInput(BaseModel):
    resource: StagedUploadTargetGenerateUploadResource
    filename: str
    mime_type: str = Field(alias="mimeType")
    http_method: Optional[StagedUploadHttpMethodType] = Field(
        alias="httpMethod", default=StagedUploadHttpMethodType.PUT
    )
    file_size: Optional[int] = Field(alias="fileSize", default=None)


class UniqueMetafieldValueInput(BaseModel):
    namespace: Optional[str] = None
    key: str
    value: str


class UnitPriceMeasurementInput(BaseModel):
    quantity_value: Optional[float] = Field(alias="quantityValue", default=None)
    quantity_unit: Optional[UnitPriceMeasurementMeasuredUnit] = Field(
        alias="quantityUnit", default=None
    )
    reference_value: Optional[int] = Field(alias="referenceValue", default=None)
    reference_unit: Optional[UnitPriceMeasurementMeasuredUnit] = Field(
        alias="referenceUnit", default=None
    )


class VariantOptionValueInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    linked_metafield_value: Optional[str] = Field(
        alias="linkedMetafieldValue", default=None
    )
    option_id: Optional[str] = Field(alias="optionId", default=None)
    option_name: Optional[str] = Field(alias="optionName", default=None)


class WeightInput(BaseModel):
    value: float
    unit: WeightUnit


InventoryItemInput.model_rebuild()
InventoryItemMeasurementInput.model_rebuild()
OptionSetInput.model_rebuild()
ProductSetIdentifiers.model_rebuild()
ProductSetInput.model_rebuild()
ProductVariantSetInput.model_rebuild()
