# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/shopify_sync/graphql/shopify

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationStatus


class ProductSetBulkRun(BaseModel):
    bulk_operation_run_mutation: Optional[
        "ProductSetBulkRunBulkOperationRunMutation"
    ] = Field(alias="bulkOperationRunMutation")


class ProductSetBulkRunBulkOperationRunMutation(BaseModel):
    bulk_operation: Optional[
        "ProductSetBulkRunBulkOperationRunMutationBulkOperation"
    ] = Field(alias="bulkOperation")
    user_errors: list["ProductSetBulkRunBulkOperationRunMutationUserErrors"] = Field(
        alias="userErrors"
    )


class ProductSetBulkRunBulkOperationRunMutationBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus


class ProductSetBulkRunBulkOperationRunMutationUserErrors(BaseModel):
    field: Optional[list[str]]
    message: str


ProductSetBulkRun.model_rebuild()
ProductSetBulkRunBulkOperationRunMutation.model_rebuild()
