# Generated by ariadne-codegen
# Source: /Users/cbusillo/Developer/odoo-ai/addons/shopify_sync/graphql/shopify

from typing import Optional

from pydantic import AnyUrl, Field

from .base_model import BaseModel


class StagedUploadsCreate(BaseModel):
    staged_uploads_create: Optional["StagedUploadsCreateStagedUploadsCreate"] = Field(
        alias="stagedUploadsCreate"
    )


class StagedUploadsCreateStagedUploadsCreate(BaseModel):
    staged_targets: Optional[
        list["StagedUploadsCreateStagedUploadsCreateStagedTargets"]
    ] = Field(alias="stagedTargets")
    user_errors: list["StagedUploadsCreateStagedUploadsCreateUserErrors"] = Field(
        alias="userErrors"
    )


class StagedUploadsCreateStagedUploadsCreateStagedTargets(BaseModel):
    url: Optional[AnyUrl]
    parameters: list["StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters"]
    resource_url: Optional[AnyUrl] = Field(alias="resourceUrl")


class StagedUploadsCreateStagedUploadsCreateStagedTargetsParameters(BaseModel):
    name: str
    value: str


class StagedUploadsCreateStagedUploadsCreateUserErrors(BaseModel):
    field: Optional[list[str]]
    message: str


StagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreate.model_rebuild()
StagedUploadsCreateStagedUploadsCreateStagedTargets.model_rebuild()
