#!/usr/bin/env bash

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

if [[ "${TRACE-}" == "1" ]]; then
  set -x
fi

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Ensure we can elevate when needed (Codex Cloud runs as non-root by default).
if command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  SUDO=""
fi

if [[ -z "$SUDO" && "$(id -u)" -ne 0 ]]; then
  log "sudo is required to install system packages"
  exit 1
fi

# Detect package manager commands upfront.
APT_GET="${SUDO:+$SUDO }apt-get"

log "Installing system packages"
$APT_GET update -y
$APT_GET install -y git openssh-client rsync software-properties-common curl ripgrep ca-certificates

log "Adding chromium PPA"
"${SUDO:+$SUDO }add-apt-repository" -y ppa:xtradeb/apps
$APT_GET update -y
$APT_GET install -y chromium fonts-liberation libu2f-udev

# Basic database tooling for local Postgres usage when desired.
$APT_GET install -y postgresql postgresql-client

log "Cleaning apt caches"
$APT_GET clean
${SUDO:+$SUDO }rm -rf /var/lib/apt/lists/*

log "Ensuring uv is available"
if ! command -v uv >/dev/null 2>&1; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

export PATH="$HOME/.local/bin:$PATH"

if [[ -d "$HOME/.local/bin" ]]; then
  if [[ -n "$SUDO" || -w /usr/local/bin ]]; then
    for bin in "$HOME"/.local/bin/uv*; do
      [[ -f "$bin" ]] || continue
      ${SUDO:+$SUDO }cp "$bin" /usr/local/bin/
    done
  else
    log "Skipping /usr/local/bin uv shim (no permission)"
  fi
fi

log "Preparing volume directories"
VOLUMES_ROOT="${VOLUMES_ROOT:-/volumes}"
if [[ ! -d "$VOLUMES_ROOT" ]]; then
  ${SUDO:+$SUDO }mkdir -p "$VOLUMES_ROOT"
  ${SUDO:+$SUDO }chown "$(id -u):$(id -g)" "$VOLUMES_ROOT"
fi

for subdir in addons config scripts enterprise data opt; do
  if [[ ! -d "$VOLUMES_ROOT/$subdir" ]]; then
    mkdir -p "$VOLUMES_ROOT/$subdir"
  fi
done

log "Syncing project assets into volume tree"
rsync -a --delete "$PROJECT_ROOT/addons/" "$VOLUMES_ROOT/addons/"
if [[ -d "$PROJECT_ROOT/docker/config" ]]; then
  rsync -a --delete "$PROJECT_ROOT/docker/config/" "$VOLUMES_ROOT/config/"
fi
if [[ -d "$PROJECT_ROOT/docker/scripts" ]]; then
  rsync -a --delete "$PROJECT_ROOT/docker/scripts/" "$VOLUMES_ROOT/scripts/"
fi
if [[ -f "$PROJECT_ROOT/pyproject.toml" ]]; then
  cp "$PROJECT_ROOT/pyproject.toml" "$VOLUMES_ROOT/pyproject.toml"
fi

if [[ -d "$VOLUMES_ROOT/scripts" ]]; then
  find "$VOLUMES_ROOT/scripts" -type f -name '*.sh' -exec chmod +x {} +
fi

log "Cloning Odoo Enterprise addons if configured"
ENTERPRISE_REPOSITORY="${ODOO_ENTERPRISE_REPOSITORY:-}"
ODOO_VERSION="${ODOO_VERSION:-18.0}"
ENTERPRISE_TARGET="$VOLUMES_ROOT/enterprise"

if [[ -n "$ENTERPRISE_REPOSITORY" ]]; then
  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    log "GITHUB_TOKEN not provided; skipping enterprise clone"
  else
    REMOTE_URL="https://${GITHUB_TOKEN}@github.com/${ENTERPRISE_REPOSITORY}"
    if [[ -d "$ENTERPRISE_TARGET/.git" ]]; then
      git -C "$ENTERPRISE_TARGET" fetch --depth 1 origin "$ODOO_VERSION"
      git -C "$ENTERPRISE_TARGET" reset --hard FETCH_HEAD
    else
      rm -rf "$ENTERPRISE_TARGET"
      git clone --branch "$ODOO_VERSION" --single-branch --depth 1 "$REMOTE_URL" "$ENTERPRISE_TARGET"
    fi
  fi
else
  log "ODOO_ENTERPRISE_REPOSITORY is empty; skipping clone"
fi

log "Preparing supplemental Python targets"
EXTRA_ROOT="$VOLUMES_ROOT/opt"
for folder in odoo-cleanup odoo-upgrade odoo-stubs; do
  mkdir -p "$EXTRA_ROOT/$folder"
done

UV_BIN="$(command -v uv)"
"$UV_BIN" pip install --no-deps --target="$EXTRA_ROOT/odoo-cleanup" \
  odoo-addon-database-cleanup --extra-index-url https://wheelhouse.odoo-community.org/oca-simple/
"$UV_BIN" pip install --target="$EXTRA_ROOT/odoo-upgrade" git+https://github.com/odoo/upgrade-util
"$UV_BIN" pip install --target="$EXTRA_ROOT/odoo-stubs" git+https://github.com/odoo-ide/odoo-stubs@18.0

log "Configuring Python import paths"
PYTHON_BIN="${PYTHON_BIN:-$(command -v python${PYTHON_VERSION:-} 2>/dev/null || command -v python3)}"
USER_SITE="$($PYTHON_BIN -m site --user-site)"
mkdir -p "$USER_SITE"

ODOO_SOURCE_PATH="${ODOO_SOURCE_PATH:-/odoo}"
cat <<EOF >"$USER_SITE/odoo_local.pth"
$ODOO_SOURCE_PATH
EOF

cat <<EOF >"$USER_SITE/odoo_enterprise.pth"
$VOLUMES_ROOT/enterprise
EOF

cat <<EOF >"$USER_SITE/upgrade_utils.pth"
$EXTRA_ROOT/odoo-upgrade
EOF

cat <<EOF >"$USER_SITE/database_cleanup.pth"
$EXTRA_ROOT/odoo-cleanup
EOF

cat <<EOF >"$USER_SITE/odoostubs.pth"
$EXTRA_ROOT/odoo-stubs
EOF

log "Persisting runtime environment variables"
RUNTIME_ENV="$VOLUMES_ROOT/config/runtime-env.sh"
mkdir -p "$(dirname "$RUNTIME_ENV")"
{
  echo "# Generated by tools/codex_cloud/setup.sh"
  echo "# shellcheck disable=SC2148"
  for var in \
    ODOO_DB_HOST \
    ODOO_DB_PORT \
    ODOO_DB_NAME \
    ODOO_DB_USER \
    ODOO_DB_PASSWORD \
    ODOO_BASE_URL \
    ODOO_DEV_MODE \
    ODOO_UPDATE \
    ODOO_KEY \
    SHOPIFY_STORE_URL \
    SHOPIFY_STORE_URL_KEY \
    SHOPIFY_API_TOKEN \
    SHOPIFY_API_VERSION \
    SHOPIFY_WEBHOOK_KEY; do
    if [[ -n "${!var-}" ]]; then
      printf 'export %s=%q\n' "$var" "${!var}"
    fi
  done
} >"${RUNTIME_ENV}.tmp"
mv "${RUNTIME_ENV}.tmp" "$RUNTIME_ENV"
chmod 600 "$RUNTIME_ENV"

log "Installing project Python dependencies"
if [[ -x "$VOLUMES_ROOT/scripts/install_prod_requirements.sh" ]]; then
  "$VOLUMES_ROOT/scripts/install_prod_requirements.sh"
fi

if [[ "${COMPOSE_BUILD_TARGET:-development}" == "development" && -x "$VOLUMES_ROOT/scripts/install_dev_requirements.sh" ]]; then
  "$VOLUMES_ROOT/scripts/install_dev_requirements.sh"
fi

PATCH_TARGET="/odoo/odoo/addons/base/models/ir_ui_view.py"
PATCH_FILE="$PROJECT_ROOT/patches/fix_dev_mode_validation.patch"
if [[ -f "$PATCH_FILE" && -f "$PATCH_TARGET" ]]; then
  if ! grep -q "Skipping validation for unresolved stat button xmlid" "$PATCH_TARGET"; then
    log "Applying development patch"
    (cd / && patch -p0 < "$PATCH_FILE")
  else
    log "Patch already applied; skipping"
  fi
fi

HOOK_SETUP_FILE="$VOLUMES_ROOT/scripts/hook_setup"
if [[ -f "$HOOK_SETUP_FILE" ]]; then
  ${SUDO:+$SUDO }cp "$HOOK_SETUP_FILE" /hook_setup
fi

log "Starting PostgreSQL cluster"
"$PROJECT_ROOT/tools/codex_cloud/start_services.sh"

log "Setup complete"
