from . import res_partner
from . import helpdesk_ticket
from . import account_move
from . import product_template
from . import identifier_index
from . import sale_order
from . import device_model_family
from . import device_model
from . import device
from . import transport_order
from . import transport_order_device
from . import intake_order
from . import intake_order_device
from . import diagnostic_test
from . import diagnostic_order
from . import diagnostic_order_device
from . import repair_issue
from . import repair_batch
from . import repair_batch_device
from . import repair_batch_device_issue
from . import repair_batch_device_part
